# Generated by Django 2.2.5 on 2020-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeit', '0002_show_cr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='cast',
            field=models.TextField(default='ahmed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='ahmed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='director',
            field=models.TextField(default='ahmed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='poster',
            field=models.ImageField(null=True, upload_to='image\\'),
        ),
    ]
