# Generated by Django 2.2.5 on 2020-07-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeit', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.CharField(default='test episode', max_length=500),
            preserve_default=False,
        ),
    ]
