# Generated by Django 2.2.5 on 2020-07-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeit', '0005_episode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='banner',
            field=models.ImageField(null=True, upload_to='image\\'),
        ),
    ]
